### ISSUE TITLE
[WARN] [deprecated] The adapter astro-vercel-edge is using a deprecated signature of the 'app.render()' method.

### ISSUE THREAD

**Issue by bizz84** [mayank99/astro-vercel-edge#1]
I'm using this library to deploy my Astro site with Vercel Edge.

Since Astro 4.x, my Vercel logs show a bunch of warnings about this issue:

> 11:51:06 [WARN] [deprecated] The adapter astro-vercel-edge is using a deprecated signature of the 'app.render()' method. From Astro 4.0, locals and routeData are provided as properties on an optional object to this method. Using the old signature will cause an error in Astro 5.0. See https://github.com/withastro/astro/pull/9199 for more information.

Example:

<img width="985" alt="Xnapper-2024-04-22-10 37 23" src="https://github.com/mayank99/astro-vercel-edge/assets/153167/c4d35da8-86e3-4cf5-80e3-b40069adc0d4">

The relevant change was merged here:

- [Switch app.render signature #9199](https://github.com/withastro/astro/pull/9199)

Accordingly, I believe this library should be updated as well.

@mayank99 thank you so much for creating this library, I've been happily using it in production!

**Comment by mayank99** [comment]
Fixed in 1.0.4
